spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
og:
  lp:
    artist:
      csv-path: artists.csv
    label:
      csv-path: labels.csv
    record:
      csv-path: records.csv
