version: '3'
services:
  lp-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lp
    ports:
      - '5434:5432'
    container_name: lp-postgres